language: node_js
node_js:
  - '10'
services:
  - postgresql
before_script:
  - psql -c 'create database biztime;' -U postgres
  - psql < data.sql
before_install:
- npm update
install:
- npm install
- npm install --save-dev jest
script:
- npm test